config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :users
  resources :preferences
  resources :pictures
  resources :sessions


  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'house/new' => 'houses#new', as: :add_new_house

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :check_login, except: [:show]
  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
    @active_houses = House.active
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
    @house.pictures.build
  end

  # GET /houses/1/edit
  def edit
    @house.pictures.build
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        @house.pictures.build
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      set_user_id
      params.require(:house).permit(:user_id, :neighborhood, :price, :street_1, :street_2, :city, :state, :zip, :active, :season, :gender, :smoking, :drinking, :pets_allowed, :furnished, :house_type, :laundry, :utilities_included, :description, :parking, :num_of_bedrooms, :num_of_bathrooms, :private_room, :private_bath, pictures_attributes: [:id, :house_id, :picture])
    end

    def set_user_id
      params[:house][:user_id] = current_user.id
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<div class="container">
  <div class="login">
  <%= form_for@house, :html => { :multipart => true } do |f| %>
    <% if @house.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>
        <ul>
        <% @house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 space">
        <%= f.fields_for :pictures do |ff| %>
          <div class="field">
            <%= ff.label :picture %><br />
            <%= ff.file_field :picture %>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :neighborhood %><br>
          <%= f.select(:neighborhood, House::NEIGHBORHOODS_LIST, prompt: "Select ...") %>
        </div>
        <div class="field">
          <%= f.label :house_type %><br>
          <%= f.select(:house_type, House::HOUSE_TYPE_LIST, prompt: "Select ...") %>
        </div>
        <div class="field">
          <%= f.label :street_1 %><br>
          <%= f.text_field :street_1 %>
        </div>
        <div class="field">
          <%= f.label :street_2 %><br>
          <%= f.text_field :street_2 %>
        </div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.select(:state, House::STATES_LIST, prompt: "Select ...") %>
        </div>
        <div class="field">
          <%= f.label :zip %><br>
          <%= f.text_field :zip %>
        </div>
      </div>
      <div class="col-md-4 space">
        <div class="field">
          <%= f.label :season %><br>
          <%= f.select(:season, House::SEASONS_LIST, prompt: "Select ...") %>
        </div>
        <div class="field">
          <%= f.label :price_per_month %><br>
          <%= f.text_field :price %>
        </div>
        <div class="field">
          <%= f.label :utilities_included %><br>
          <%= f.check_box :utilities_included %>
        </div>
        <div class="field">
          <%= f.label :number_of_bedrooms %><br>
          <%= f.text_field :num_of_bedrooms %>
        </div>
        <div class="field">
          <%= f.label :number_of_bathrooms %><br>
          <%= f.text_field :num_of_bathrooms %>
        </div>
        <div class="field">
          <%= f.label :private_room %><br>
          <%= f.check_box :private_room %>
        </div>
        <div class="field">
          <%= f.label :private_bath %><br>
          <%= f.check_box :private_bath %>
        </div>
        <div class="field">
          <%= f.label :gender %><br>
          <%= f.select(:gender, House::GENDER_LIST, prompt: "Select...") %>
        </div>
      </div>
      <div class="col-md-4 space">
        
        <div class="field">
          <%= f.label :laundry_available %><br>
          <%= f.select(:laundry, House::LAUNDRY_LIST, prompt: "Select ...") %>
        </div>
        <div class="field">
          <%= f.label :smoking_friendly %><br>
          <%= f.check_box :smoking %>
        </div>
        <div class="field">
          <%= f.label :alcohol_friendly %><br>
          <%= f.check_box :drinking %>
        </div>
        <div class="field">
          <%= f.label :pets_allowed %><br>
          <%= f.check_box :pets_allowed %>
        </div>
        <div class="field">
          <%= f.label :furnished %><br>
          <%= f.check_box :furnished %>
        </div>
        <% if controller.action_name == 'edit' %>
          <div class="field">
            <%= f.label :available %><br>
            <%= f.check_box :active %>
          </div>
        <% else %>
          <%= f.hidden_field :active, value: true %>
        <% end %>
        <div class="field">
          <%= f.label :parking_available %><br>
          <%= f.check_box :parking %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
        <div class="actions">
        <%= f.submit 'Submit', :class => 'btn btn-default submit' %>
        </div>
      </div>

  <% end %>
    </div>
  </div>
</div>

app/views/houses/_house_details.erb
<h4><strong>House Information </strong>
  <% if current_user.id == @house.user_id %>
    <%= link_to image_tag("u1257.png"), edit_house_path(@house) %>
  <% end %>
</h4>
<br><br>
<div class="col-xs-4">

	<% if @house.pictures.first == nil %>
    	<%= image_tag 'empty_house.jpg', size: "300x200", class: "left" %>
  	<% else %>
    	<%= image_tag @house.pictures.first.picture, width: "100%" %>
  	<% end %>

	<br><br>
	<h3 style="text-align:left;float:left"><%= @house.neighborhood %></h3>
    <h3 style="text-align:right;float:right"><%= number_to_currency(@house.price.to_i) %></h3>
    <br>
				<hr>
    <p><%= "#{@house.street_1}, #{@house.city}, #{@house.state} #{@house.zip}" %></p>

</div>
<div class="col-xs-5">
    
    <p><strong>Specified Gender: </strong><%= @house.gender %></p>
    <p><strong>Availability: </strong><%= @house.season %></p>
    <p><strong>Smoking: </strong>
      <% if @house.smoking == true %>
        Allowed
      <% else %>
        Not Allowed
      <% end %>
      </p>
    <p><strong>Drinking: </strong>
    <% if @house.drinking == true %>
      Allowed
    <% else %>
      Not Allowed
    <% end %>
    </p>
    <p><strong>Pets: </strong>
    <% if @house.pets_allowed == true %>
      Allowed
    <% else %>
      Not Allowed
    <% end %>
    </p>
    <p><strong>Furnished: </strong>
      <% if @house.furnished == true %>
      Yes
      <% else %>
        No
      <% end %>
    <p><strong>Bathroom: </strong>
    <% if @house.private_bath == true %>
      Private
    <% else %>
      Shared
    <% end %>
    </p>
    <p><strong>Type: </strong><%= @house.house_type %></p>
    <p><strong>Laundry: </strong><%= @house.laundry %></p>
    <p><strong>Utilities Included: </strong>
    <% if @house.utilities_included == true %>
      Yes
    <% else %>
      No
    <% end %>
    </p>

</div>
<div class="col-xs-3">
  <i><%= @house.description %></i>
  <p><strong>Parking: </strong>
    <% if @house.parking == true %>
      Yes
    <% else %>
      No
    <% end %>
    </p>
  <p><strong>Number of bedrooms: </strong><%= @house.num_of_bedrooms.to_i %></p>
  <p><strong>Number of bathrooms: </strong><%= @house.num_of_bathrooms.to_i %></p>
</div>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<% if @active_houses.empty? %>
  <h5><center><i>There are currently no available houses. Please check back again!</i></center></h5>
<% else %>
    <div id="main-container" class="container-fluid">
      <div id="main content" class="col-xs-9">
      <% @active_houses.each do |house| %>
        <div class="row">
          <div class="card">
          <div class="card-block">
            <div class="col-xs-2">
              <% if house.pictures.blank? %>
                <%= image_tag 'empty_house.jpg', :class => "img", size: "100x100", class: "left" %>
              <% else %>
               <%= image_tag house.pictures.first.picture, :class => "img-circle", size: "100x100" %>
              <% end %>
            </div>
            <div class="col-xs-2">     
              <h4 class="house-title"><%= house.neighborhood %></h4>
              <p><%= house.street_1 %><br>
              <%= house.city%>, <%= house.state%></p>
            </div>
            <div class="col-xs-5">
              <h6 class="house-title"><%= number_to_currency(house.price) %>/month</h6>
              <p><%= house.description%></p>
              <p><%= link_to 'View House', house_path(house)%></p>
            </div>
            <div class="col-xs-2">
              <i class="fa fa-envelope"></i><p class="fa_contact"><%= mail_to house.user.email %></p><br>
              <i class="fa fa-phone"></i><p class="fa_contact"><%= number_to_phone(house.user.phone) %></p><br>
              <% if house.user.fb_link.blank? %>
              <% else %>
              <i class="fa fa-facebook-square"></i><p class="fa_contact"><%= house.user.fb_link %></p><br>
              <% end %>
            </div>
          </div>
          </div>
        </div>
      <% end %>
      </div>
      
      <div id="sidebar" class="col-xs-3">
        <div class="card">
          <div class="card-block">
            <form name="user_search_filters">
            <div class="user_dropdown">
              <h5><center>Filters</center></h5>
              <hr>
              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Neighborhood</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Bloomfield">Bloomfield</option>
                    <option value="Downtown">Downtown</option>
                    <option value="East Liberty">East Liberty</option>
                    <option value="Highland Park">Highland Park</option>
                    <option value="Homestead">Homestead</option>
                    <option value="North Side">North Side</option>
                    <option value="Oakland">Oakland</option>
                    <option value="Point Breeze">Point Breeze</option>
                    <option value="Shadyside">Shadyside</option>
                    <option value="South Side">South Side</option>
                    <option value="Squirrel Hill">Squirrel Hill</option>
                    <option value="Strip District">Strip District</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Gender</p>
                </div>
                <div class="col-xs-2">
                <select>
                  <option value="" disabled selected="selected">Select...</option>
                  <option value="Female">Female</option>
                  <option value="Male">Male</option>
                  <option value="Not Specified">Not Specified</option>
                </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Season</p>
                </div>
                <div class="col-xs-2">
                  <select width="100px">
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Winter">Winter</option>
                    <option value="Spring">Spring</option>
                    <option value="Summer">Summer</option>
                    <option value="Fall">Fall</option>
                    <option value="Year">Year</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Smoking?</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="true">True</option>
                    <option value="false">False</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Drinking?</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="true">True</option>
                    <option value="false">False</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Room</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Single">Single</option>
                    <option value="Double">Double</option>
                    <option value="No Preference">No Preference</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Price Limit:</p>
                </div>
                <div class="col-xs-1">
                  <input type="text">
                </div>
              </div>

              <center><button type="submit">Apply Filters</button></center>
            </div>
            </form>

          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/houses/new.html.erb
<h3>New House</h3>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<div id="main-container" class="container-fluid">
  <div id="main content" class="col-xs-9 offset-xs-1">
    <div class="row">
      <div class="card">
        <div class="card-block">
            <div class="col-xs-12">
              <%= render 'house_details' %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>