config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :users
  resources :preferences
  resources :pictures
  resources :sessions


  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'house/new' => 'houses#new', as: :add_new_house

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/partials/_footer.html.erb
<!--code for nav bar goes here! -->
<div class="footer-container">
	<i class="fa fa-copyright fa-lg">
		
	</i>

	<span class="footer_text">2016 Casa</span>

</div>

app/views/partials/_nav.html.erb
<!--code for nav bar goes here! -->
<nav class="navbar">
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <%= link_to(image_tag('is_logo.png', :size => "70x70", :style => "padding:0px 0px 0px 20px;"),
              home_path,{ :class=> "brand-logo left" }) %>
    </li>
    <li class="nav-item">
      <%= link_to "All Homes", houses_path, { :class=>"nav-link top_nav left_link", :style => "padding:10px 0px 10px 15px;" } %>
    </li>
    <li class="nav-item">
      <%= link_to "All People", users_path, { :class=>"nav-link top_nav left_link", :style => "padding:10px 0px 10px 15px;" } %>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-xs-right">
  	<li class="nav-item"><%= link_to "Your Account", user_path(current_user.id), { :class=>"nav-link top_nav", :style => "padding:10px 0px 10px 15px;" } %></li>
  	<li class="nav-item"><%= link_to 'Logout', logout_path, { :class=>"nav-link top_nav", :style => "padding:10px 30px 10px 15px;" } %></li>
  </ul>
</nav>