config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :users
  resources :preferences
  resources :pictures
  resources :sessions


  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'house/new' => 'houses#new', as: :add_new_house

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use built-in rails support for password protection
  has_secure_password

  mount_uploader :picture, PhotoUploader

  # Relationships
  has_one :preference, :dependent => :destroy
  has_many :houses

  accepts_nested_attributes_for :preference

  #array for Enumerated Values
  GENDER_LIST = [['Male', 'Male'], ['Female', 'Female'], ['Not Specified', 'Not Specified']]

  # Scopes
  scope :by_gender,      -> { order(:gender) }
  scope :alphabetical,  -> { order(:last_name).order(:first_name) }

  # Validations
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_inclusion_of :gender, in: GENDER_LIST.map{|key, value| value}, message: "is not a valid option"
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: "does not match"
  validates_length_of :password, minimum: 4, message: "must be at least 4 characters long", allow_blank: true
  validates_presence_of :last_name, :first_name
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

  # Callbacks
  before_save :reformat_phone

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end

  def proper_name
    "#{first_name} #{last_name}"
  end

  def owner?
    return false if is_owner.nil?
    is_owner == true
  end

  # Private methods
  private
  def reformat_phone
    self.phone = self.phone.to_s.gsub(/[^0-9]/,"")
  end

  # For use in authorizing with CanCan
#  ROLES = [['Administrator', :admin],['Baker', :baker],['Shipper', :shipper],['Customer',:customer]]

#  def role?(authorized_role)
#    return false if role.nil?
#    role.downcase.to_sym == authorized_role
#  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @my_house = @user.houses.first
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_preference
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      if !current_user
        session[:user_id] = @user.id
      end
      redirect_to root_url, notice: "Account created successfully!"
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :username, :password, :password_confirmation, :is_admin, :first_name, :last_name, :email, :phone, :fb_link, :picture, :gender, :is_owner, :description, preference_attributes: [:id, :user_id, :neighborhood_pref, :gender_pref, :price_limit_pref, :room_pref, :season_pref, :smoking_pref, :drinking_pref])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_details.erb
<center>
<% if @user.picture.blank? %>
  <%= image_tag 'empty_user_picture.png', :class => "img-circle", size: "200x200", class: "middle" %>
<% else %>
  <%= image_tag @user.picture, :class => "img-circle", size: "200x200" %>
<% end %>

<br><br>
<h2> <strong><%= @user.proper_name %></strong>
  <% if current_user.id == @user.id %>
    <%= link_to image_tag("u1257.png"), edit_user_path(@user) %> </h2>
  <% end %>

<h4> <%= "(#{@user.username})" %> </h4>
<br>
<% if @user.gender == "Female" %>
  <%= image_tag 'u1261.png' %>
<% else %>
  <%= image_tag 'male.png', size: "20x30" %>
<% end %>
</center>
<br>
<div id="contact_user">
  <%= image_tag 'u1176.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= @user.email %></p><br>
  <%= image_tag 'u1174.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= @user.phone %></p><br>
  <% if @user.fb_link.blank? %>
  <% else %>
  <%= image_tag 'u1172.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= @user.fb_link %></p>
  <% end %>
  <br><br>
  <p><%= @user.description %></p>
</div>

app/views/users/_account_preferences.erb
<h4><strong>Account Preferences </strong>
<% if current_user.id == @user.id %>
    <%= link_to image_tag("u1257.png"), edit_user_path(@user) %> </h2>
  <% end %></h4>

<br><br>
<p><strong>Neighborhood Preference: </strong><%= @user.preference.neighborhood_pref %></p>
<p><strong>Gender Preference: </strong><%= @user.preference.gender_pref %></p>
<p><strong>Price Limit: </strong><%= "$ #{@user.preference.price_limit_pref.to_i}" %></p>
<p><strong>Room Preference: </strong><%= @user.preference.room_pref %></p>
<p><strong>Season Preference: </strong><%= @user.preference.season_pref %></p>
<p><strong>Smoking: </strong>
  <% if @user.preference.smoking_pref == true %>
    Yes
  <% else %>
    No
  <% end %>
  </p>
<p><strong>Drinking: </strong>
<% if @user.preference.drinking_pref == true %>
  Yes
<% else %>
  No
<% end %>
</p>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true} do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if controller.action_name == 'new' || controller.action_name == 'create' %>
    <div class="col-md-6">
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>



 <!-- <div class="field">
     f.label  is_admin <br>
     f.check_box  is_admin 
  </div> -->
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fb_link, "Your Facebook profile link" %><br>
    <%= f.text_field :fb_link %>
  </div>
  </div>
  <div class="col-md-6">
  <div class="field">
    <%= f.label :picture, "Your Profile Picture" %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select(:gender, User::GENDER_LIST, prompt: "Select...") %>
  </div>
  <!-- Not a field that we will allow user to check. System will change this automatically once they add a house 
  <div class="field">
     f.label  is_owner <br>
     f.check_box  is_owner 
  </div> -->
  <div class="field">
    <%= f.label :description, "Describe yourself!" %><br>
    <%= f.text_area :description %>
  </div>

    <!--Nested attributes form for preferences of a user -->
    <%= f.fields_for :preference do |ff| %>
      <div>
        <%= ff.label :neighborhood_pref, "Neighborhood Preference" %><br>
        <%= ff.select(:neighborhood_pref, Preference::NEIGHBORHOODS_LIST, prompt: "Select...") %>
      </div>
      <div>
        <%= ff.label :gender_pref, "Gender Preference" %><br>
        <%= ff.select(:gender_pref, Preference::GENDERS_LIST, prompt: "Select...") %>
      </div>
      <div>
        <%= ff.label :price_limit_pref, "What price do you prefer?" %><br>
        <%= ff.text_field :price_limit_pref %>
      </div>
      <div>
        <%= ff.label :room_pref, "What room type do you prefer?" %><br>
        <%= ff.select(:room_pref, Preference::ROOMS_LIST, prompt: "Select...") %>
      </div>
      <div>
        <%= ff.label :season_pref, "When do you want to rent?" %><br>
        <%= ff.select(:season_pref, Preference::SEASONS_LIST, prompt: "Select...") %>
      </div>
      <div>
        <%= ff.label :smoking_pref, "Are you okay with smoking?" %><br>
        <%= ff.check_box :smoking_pref %>
      </div>
      <div>
        <%= ff.label :drinking_pref, "Are you okay with drinking?" %><br>
        <%= ff.check_box :drinking_pref %>
      </div>
    <% end %>


  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-default submit' %>
  </div>
  </div>
<% end %>

app/views/users/_house_details.erb
<h4><strong>House Information </strong><%= link_to image_tag("u1257.png"), edit_house_path(@my_house) %></h4>
<br><br>
<div class="col-xs-7">

	<% if @my_house.pictures.first == nil %>
    	<%= image_tag 'empty_house.jpg', size: "300x200", class: "left" %>
  	<% else %>
    	<%= image_tag @my_house.pictures.first.picture, width: "100%" %>
  	<% end %>

	<br><br>
	<h3 style="text-align:left;float:left"><%= @my_house.neighborhood %></h3>
    <h3 style="text-align:right;float:right"><%= "$ #{@my_house.price.to_i}" %></h3>
    <br>
				<hr>
    <p><%= "#{@my_house.street_1}, #{@my_house.city}, #{@my_house.state} #{@my_house.zip}" %></p>

</div>
<div class="col-xs-5">
    
    <p><strong>Specified Gender: </strong><%= @my_house.gender %></p>
    <p><strong>Availability: </strong><%= @my_house.season %></p>
    <p><strong>Smoking: </strong>
      <% if @my_house.smoking == true %>
        Allowed
      <% else %>
        Not Allowed
      <% end %>
      </p>
    <p><strong>Drinking: </strong>
    <% if @my_house.drinking == true %>
      Allowed
    <% else %>
      Not Allowed
    <% end %>
    </p>
    <p><strong>Pets: </strong>
    <% if @my_house.pets_allowed == true %>
      Allowed
    <% else %>
      Not Allowed
    <% end %>
    </p>
    <p><strong>Furnished: </strong><%= @my_house.furnished %></p>
    <p><strong>Bathroom: </strong>
    <% if @my_house.private_bath == true %>
      Private
    <% else %>
      Shared
    <% end %>
    </p>
    <p><strong>Type: </strong><%= @my_house.house_type %></p>
    <p><strong>Laundry: </strong><%= @my_house.laundry %></p>
    <p><strong>Utilities Included: </strong>
    <% if @my_house.utilities_included == true %>
      Yes
    <% else %>
      No
    <% end %>
    </p>

    <p><%= @my_house.description %></p>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if !logged_in? then check_login  %><% end %>

<% if @users.empty? %>
  <h5><center><i>There are currently no users to view. Please check back again!</i></center></h5>
<% else %>
    <div id="main-container" class="container-fluid">
      <div id="main content" class="col-xs-9">
      <% @users.each do |user| %>
        <div class="row">
          <div class="card">
          <div class="card-block">
            <div class="col-xs-2">
              <% if user.picture.blank? %>
                <%= image_tag 'empty_user_picture.png', :class => "img-circle", size: "100x100", class: "left" %>
              <% else %>
                <%= image_tag user.picture, :class => "img-circle", size: "100x100" %>
              <% end %>
            </div>
            <div class="col-xs-2">     
              <h4 class="card-title"><%= user.proper_name %></h4>
            </div>
            <div class="col-xs-5">
              <p class="card-text"><%= user.description %></p>
            </div>
            <div class="col-xs-2">
              <%= image_tag 'u1176.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.email %></p><br>
              <%= image_tag 'u1174.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.phone %></p><br>
              <%= image_tag 'u1172.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.fb_link %></p>
            </div>
          </div>
          </div>
        </div>
      <% end %>
      </div>
      
      <div id="sidebar" class="col-xs-3">
        <div class="card">
          <div class="card-block">
            <form name="user_search_filters">
            <div class="user_dropdown">
              <h5><center>Filters</center></h5>
              <hr>
              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Neighborhood</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Bloomfield">Bloomfield</option>
                    <option value="Downtown">Downtown</option>
                    <option value="East Liberty">East Liberty</option>
                    <option value="Highland Park">Highland Park</option>
                    <option value="Homestead">Homestead</option>
                    <option value="North Side">North Side</option>
                    <option value="Oakland">Oakland</option>
                    <option value="Point Breeze">Point Breeze</option>
                    <option value="Shadyside">Shadyside</option>
                    <option value="South Side">South Side</option>
                    <option value="Squirrel Hill">Squirrel Hill</option>
                    <option value="Strip District">Strip District</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Gender</p>
                </div>
                <div class="col-xs-2">
                <select>
                  <option value="" disabled selected="selected">Select...</option>
                  <option value="Female">Female</option>
                  <option value="Male">Male</option>
                  <option value="Not Specified">Not Specified</option>
                </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Season</p>
                </div>
                <div class="col-xs-2">
                  <select width="100px">
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Winter">Winter</option>
                    <option value="Spring">Spring</option>
                    <option value="Summer">Summer</option>
                    <option value="Fall">Fall</option>
                    <option value="Year">Year</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Smoking?</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="true">True</option>
                    <option value="false">False</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Drinking?</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="true">True</option>
                    <option value="false">False</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Room</p>
                </div>
                <div class="col-xs-2">
                  <select>
                    <option value="" disabled selected="selected">Select...</option>
                    <option value="Single">Single</option>
                    <option value="Double">Double</option>
                    <option value="No Preference">No Preference</option>
                  </select>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-5">
                  <p class="user_filter">Price Limit:</p>
                </div>
                <div class="col-xs-1">
                  <input type="text">
                </div>
              </div>

              <center><button type="submit">Apply Filters</button></center>
            </div>
            </form>

          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/users/new.html.erb
<div class="container">
	<div class="create_account">
		<div class="row logo">
	      <div class="col-md-4"></div>
	      <div class="col-md-4">
	        <%= link_to root_path do %>
	          <%= image_tag("is_logo.png", size: "150x193", :class => "casa_logo") %>
        <% end %>
     	</div>
       <div class="col-md-4"></div>
		</div>
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6 login info">
				<ul class="nav nav-tabs tabs">
		          <li class="nav-item">
		            <%= link_to 'Log In', login_path, :class=>"nav-link" %>
		          </li>
		          <li class="nav-item">
		            <%= link_to 'Create Account', signup_path, :class=>"nav-link active" %>
		          </li>
		        </ul>
		        <div class="account_form">
					<%= render 'form' %>

				</div>
			</div>
			<div class="col-md-3"></div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div id="main-container" class="container-fluid">
  <div id="main content" class="col-xs-12">
    <div class="row">
      <div class="card">
        <div class="card-block">
          <% if current_user.owner? %>

            <div class="col-xs-3" id="account-details">
              <%= render 'account_details' %>
            </div>
            <div class="col-xs-3" id="account-preferences">
              <%= render 'account_preferences' %>
            </div>
            <div class="col-xs-6" id="house-details">
              <%= render 'house_details' %>
            </div>

          <% else %>
            <div class="col-xs-6" id="account-details">
              <%= render 'account_details' %>
            </div>
            <div class="col-xs-6" id="account-preferences">
              <%= render 'account_preferences' %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>