config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :users
  resources :preferences
  resources :pictures
  resources :sessions


  # Set the root url
  root :to => 'home#home'

  # Authentication routes
  get 'home' => 'home#home', as: :home
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  get 'house/new' => 'houses#new', as: :add_new_house

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    if (current_user && current_user.owner?)
      @recommended_houses = find_house_recommendations
      @recommended_users = find_user_recommendations
      @my_house = current_user.houses.active.first

    elsif (current_user)
      @recommended_houses = find_house_recommendations
    else
      redirect_to login_path
    end
  end

  def about
  end

  def privacy
  end

  def contact
  end

  private

  def find_user_recommendations
    #return a list of recommended users for a house based on their preferences
    all_users = User.all
    recommended_users = Array.new
    all_users.each do |u|
      matches = find_num_of_user_matches(u)
      #num of matches for a user to show up, will probably increase
      if (matches > 4)
          recommended_users << u
      end
    end
    return recommended_users
  end

  def find_num_of_user_matches(user)
    matches = 0
    house = current_user.houses.active.first
    if ((user.preference.gender_pref != nil) && (user.preference.gender_pref == house.gender))
      matches += 1
    end
    if ((user.preference.neighborhood_pref != nil) && (user.preference.neighborhood_pref == house.neighborhood))
      matches += 1
    end
    if ((user.preference.season_pref != nil) && (user.preference.season_pref == house.season))
      matches += 1
    end
    if ((user.preference.smoking_pref != nil) && (user.preference.smoking_pref == house.smoking))
      matches += 1
    end
    if ((user.preference.drinking_pref != nil) && (user.preference.drinking_pref == house.drinking))
      matches += 1
    end
    if ((user.preference.price_limit_pref != nil) && (user.preference.price_limit_pref > house.price))
      matches += 1
    end
    return matches
  end


  def find_house_recommendations
    # return a list of recommended houses for a user based on their preferences
    all_houses = House.all
    recommended_houses = Array.new
    all_houses.each do |h|
      matches = find_num_of_house_matches(h)
      #num of matches for a house to show up, will probably increase
      #when we get more houses in system
      if (matches > 4) 
        recommended_houses << h
      end
    end
    return recommended_houses
  end

  def find_num_of_house_matches(house)
    matches = 0
    if ((current_user.preference.gender_pref != nil) && (current_user.preference.gender_pref == house.gender))
      matches += 1
    end
    if ((current_user.preference.neighborhood_pref != nil) && (current_user.preference.neighborhood_pref == house.neighborhood))
      matches += 1
    end
    if ((current_user.preference.season_pref != nil) && (current_user.preference.season_pref == house.season))
      matches += 1
    end
    if ((current_user.preference.smoking_pref != nil) && (current_user.preference.smoking_pref == house.smoking))
      matches += 1
    end
    if ((current_user.preference.drinking_pref != nil) && (current_user.preference.drinking_pref == house.drinking))
      matches += 1
    end
    if ((current_user.preference.price_limit_pref != nil) && (current_user.preference.price_limit_pref > house.price))
      matches += 1
    end
    return matches
  end

end

app/views/home/_house_recommendations.erb
<!-- code for house recommendations goes here -->

<% if @recommended_houses.empty? %>
  <h5><center><i>There are currently no recommended houses</i></center></h5>
<% else %>

  <div class="row custom-card">
    <div class="card">
      <div class="card-block">
        <div class="col-xs-8">
          <h2 class="card-title">Recommended Homes</h2>
            <% if @recommended_houses.first.pictures.blank? %>
              <%= image_tag 'empty_house.jpg', :class => "img", width: "100%" %><br><br>
            <% else %>
              <%= image_tag @recommended_houses.first.pictures.first.picture, width: "100%" %><br><br>
            <% end %>
            <h3 style="text-align:left;float:left"><%= @recommended_houses.first.neighborhood %></h3>
            <h3 style="text-align:right;float:right"><%= "$ #{@recommended_houses.first.price.to_i}" %></h3>
            <br>
            <hr>
            <div class="col-xs-7">
              <p><%= "#{@recommended_houses.first.street_1}, #{@recommended_houses.first.city}, #{@recommended_houses.first.state} #{@recommended_houses.first.zip}" %></p>
              <p><strong>Availability: </strong><%= @recommended_houses.first.season %></p>
              <p><strong>Gender Preference: </strong><%= @recommended_houses.first.gender %></p>
              <p><strong>Smoking: </strong>
                <% if @recommended_houses.first.smoking == true %>
                  Allowed
                <% else %>
                  Not Allowed
                <% end %>
                </p>
              <p><strong>Drinking: </strong>
              <% if @recommended_houses.first.drinking == true %>
                Allowed
              <% else %>
                Not Allowed
              <% end %>
              </p>
              <p><%= @recommended_houses.first.description %></p>
              <p><%= link_to 'View House', house_path(@recommended_houses.first)%></p>
            </div>

            <div class="col-xs-5 contact col-xs-offset-8">
              <h4 class="img-contact">Contact</h4>
              <% if @recommended_houses.first.user.picture.blank? %>
                <%= image_tag 'empty_user_picture.png', :class => "img-contact", size: "50x50"%>
              <% else %>
                <%= image_tag @recommended_houses.first.user.picture, :class => "img-contact", size: "50x50" %><br>
              <% end %>
              <h4 class="img-contact"><%="#{@recommended_houses.first.user.username}"%></h4>
            </div>
            <div class="col-xs-5 contact">
              <i class="fa fa-envelope"></i><p class="fa_contact"><%= mail_to @recommended_houses.first.user.email %></p><br>
              <i class="fa fa-phone"></i><p class="fa_contact"><%= number_to_phone(@recommended_houses.first.user.phone) %></p><br>
              <% if @recommended_houses.first.user.fb_link.blank? %>
              <% else %>
              <i class="fa fa-facebook-square"></i><p class="fa_contact"><%= @recommended_houses.first.user.fb_link %></p><br>
              <% end %>
            </div>

        </div>

        <div class="col-xs-4">
          <% if @recommended_houses.drop(1).empty? %>
          <% else %>
          <h6 class="card-title">Also there's...</h6>
          <% @recommended_houses.drop(1).each do |house| %>
            <div class="row">
              <div class="col-xs-6 contact">
                <% if house.pictures.blank? %>
                  <%= image_tag 'empty_house.jpg', :class => "img", width: "100%", class: "left" %>
                <% else %>
                  <%= image_tag house.pictures.first.picture, :class => "img", width: "100%" %>
                <% end %>
              </div>
              <div class="col-xs-6">
                <p style="vertical-align:middle;"><%= house.neighborhood %></p>
              </div>
            </div>
            
            <div class="row">
              <div class="rec_contact">
                <p><%= "$ #{house.price.to_i}" %><br>
                <%= house.street_1 %><br>
                <%= "#{house.city}, #{house.state}" %>
                <%= house.zip %></p>
              </div>
            </div>
          
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_user_recommendations.erb
<!-- code for house recommendations goes here -->

<% if @recommended_users.empty? %>
  <h5><center><i>There are currently no recommended users</i></center></h5>

<% else %>
	<div class="row custom-card">
    <div class="card">
    	<div class="card-block">
        <div class="col-xs-8">
          <h2 class="card-title">Properties You're Selling</h2>
  					<%= image_tag @my_house.pictures.first.picture, width: "100%" %><br><br>
  					<h3 style="text-align:left;float:left"><%= @my_house.neighborhood %></h3>
            <h3 style="text-align:right;float:right"><%= "$ #{@my_house.price.to_i}" %></h3>
            <br>
  					<hr>
            <p><%= "#{@my_house.street_1}, #{@my_house.city}, #{@my_house.state} #{@my_house.zip}" %></p>
            <p><strong>Availability: </strong><%= @my_house.season %></p>
            <p><strong>Gender Preference: </strong><%= @my_house.gender %></p>
            <p><strong>Smoking: </strong>
              <% if @my_house.smoking == true %>
                Allowed
              <% else %>
                Not Allowed
              <% end %>
              </p>
            <p><strong>Drinking: </strong>
            <% if @my_house.drinking == true %>
              Allowed
            <% else %>
              Not Allowed
            <% end %>
            </p>
            <p><%= @my_house.description %></p>

            <div id="edit_home">
              <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_house_path(@my_house) %></button>
            </div>

  			</div>

  			<div class="col-xs-4">
          <h6 class="card-title">Recommended Renters</h6>
      		<% @recommended_users.each do |user| %>
            <div class="row">
              <div class="col-xs-6">
                <% if user.picture.blank? %>
                  <%= image_tag 'empty_user_picture.png', :class => "img-circle", width: "100%", class: "left" %>
                <% else %>
                  <%= image_tag user.picture, :class => "img-circle", width: "100%" %>
                <% end %>
              </div>
              <div class="col-xs-6">
                <p style="vertical-align:middle;"><%= user.proper_name %></p>
              </div>
            </div>
            
            <div class="row">
              <div class="rec_contact">
                <%= image_tag 'u1176.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.email %></p><br>
                <%= image_tag 'u1174.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.phone %></p><br>
                <%= image_tag 'u1172.png', :class => "contact_icon", display: "inline", size: "27x20" %><p class="contact_info"><%= user.fb_link %></p>
              </div>
            </div>
        	
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/home/home.html.erb
<!-- home page for users that are logged in -->
<div id="new_home">
  <button type="button" class="btn btn-warning"><%= link_to 'Add Your Home', add_new_house_path %></button>
</div>
<br>

<% if current_user.owner? %>
  <div id="main-container" class="container-fluid">
    <div id="main content" class="col-xs-6">
      <%= render 'user_recommendations' %>
    </div>
    
    <div id="main content" class="col-xs-6">
      <%= render 'house_recommendations' %>
    </div>
  </div>

<% else %>
  <div id="main-container" class="container-fluid">
    <div id="main content" class="col-xs-12">
      <%= render 'house_recommendations' %>
    </div>
  </div>

<% end %>